### PR TITLE
Tdiercks/fix event sorting

### LINKED ISSUE #28: Eventlog sorting doesn't work

### PR DESCRIPTION
**Pull request by TDiercks**
closes #28 
### Removed features
- Sorting in Eventlog
- Sorting in Reactions

### Fixed Bugs
- total Count with and without filters

### CODE REVIEW

File: frontend/src/components/EventLog.vue [hunk 1]
```diff
@@ -231,7 +232,11 @@ export default {
       if (params.itemsPerPage > 0) {
         try {
           const res = await eventLogClient.list(params)
+          console.log(res)
```
Comment (marcboeker) [inline frontend/src/components/EventLog.vue:235]: Please remove :)

File: server/analytics/reaction.go [hunk 2]
```diff
@@ -246,6 +246,53 @@ func (a Analytics) GetReactionCount(arg GetReactionCountParams) (int, error) {
...
+}
+
+func (a Analytics) GetReactionCountFiltered(arg GetReactionCountFilteredParams) (int, error) {
+	var count int
+
+	var identity = ""
+	var event = ""
+	if arg.UserID != "" {
+		identity = fmt.Sprintf(
+			"AND identity_id = '%s'",
```
Comment (marcboeker) [inline server/analytics/reaction.go:275]: This can be dangerous as you could inject malicious SQL. Please always escape the params. But I would suggest to use `?` instead of `%s` and append the value of `%s` to a params slice which you later supply to the `QueryRowx()` method like `QueryRowx(query, params)`.

`params` can initially be:

```
params := []string{
    arg.OrganizationID,
    arg.ActionID,
    arg.Start,
    arg.End,
}
```

File: server/platform/controllers/event_log.go [hunk 3]
```diff
@@ -45,7 +45,11 @@ func (ec EventLogController) List(c *gin.Context) {
 		if err == nil {
 			identityIDs = append(identityIDs, identity.ID)
 		} else {
-			c.AbortWithStatus(http.StatusNoContent)
+			res := responses.EventLogList{
+				Events: []responses.EventLog{},
+				Count:  0,
+			}
+			c.JSON(http.StatusOK, &res)
```
Comment (marcboeker) [inline server/platform/controllers/event_log.go:52]: Why not return an empty `responses.EventLogList{}` as the `Count` field will always be 0.

File: server/analytics/reaction.go (hunk 2 above)
Comment (TDiercks) [reply server/analytics/reaction.go:275]: function removed

File: server/platform/controllers/event_log.go [hunk 4]
```diff
@@ -45,6 +45,7 @@ func (ec EventLogController) List(c *gin.Context) {
 		if err == nil {
 			identityIDs = append(identityIDs, identity.ID)
 		} else {
+
```
Comment (marcboeker) [inline server/platform/controllers/event_log.go:48]: Please remove blank line.

File: server/analytics/event.go [hunk 5]
```diff
@@ -233,19 +234,37 @@ func (a Analytics) GetEventsForIdentities(arg GetEventsForIdentitiesParams) ([]E
...
 
-func (a Analytics) GetEventCount(organizationID uuid.UUID) (int, error) {
-	row := a.DB.QueryRowx(getEventCount, organizationID)
+func (a Analytics) GetLastDaysEventCount(organizationID uuid.UUID) (int, error) {
+	row := a.DB.QueryRowx(getLastDaysEventCount, organizationID)
 	var count int
 	return count, row.Scan(&count)
 }
 
+/*const getEventCount = `
```
Comment (marcboeker) [inline server/analytics/event.go:250]: Please remove obsolete code.
